enum TokenType {
	TokenType_Unknown,
	TokenType_String,
	TokenType_Id,
	TokenType_Integer,
	TokenType_Real,
	TokenType_Let,
	TokenType_Fn,
	TokenType_Return,
	TokenType_If,
	TokenType_Else,
	TokenType_For,
	TokenType_Break,
	TokenType_Continue,
	TokenType_ParenOpen,
	TokenType_ParenClose,
	TokenType_SquareOpen,
	TokenType_SquareClose,
	TokenType_CurlyOpen,
	TokenType_CurlyClose,
};
static const String token_type_strings[] = {
	[TokenType_Unknown] = {},
	[TokenType_String] = {},
	[TokenType_Id] = {},
	[TokenType_Integer] = {},
	[TokenType_Real] = {},
	[TokenType_ParenOpen] = str_literal("("),
	[TokenType_ParenClose] = str_literal(")"),
	[TokenType_SquareOpen] = str_literal("["),
	[TokenType_SquareClose] = str_literal("]"),
	[TokenType_CurlyOpen] = str_literal("{"),
	[TokenType_CurlyClose] = str_literal("}"),
	[TokenType_Let] = str_literal("let"),
	[TokenType_Fn] = str_literal("fn"),
	[TokenType_Return] = str_literal("return"),
	[TokenType_If] = str_literal("if"),
	[TokenType_Else] = str_literal("else"),
	[TokenType_For] = str_literal("for"),
	[TokenType_Break] = str_literal("break"),
	[TokenType_Continue] = str_literal("continue"),
};
